# Generated by Django 4.1.7 on 2023-03-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycare_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountInfo',
            new_name='Account',
        ),
    ]
