# Generated by Django 4.1.7 on 2023-03-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycare_backend', '0002_rename_accountinfo_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='userGender',
            field=models.IntegerField(default=0),
        ),
    ]
