# Generated by Django 4.1.7 on 2023-03-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycare_backend', '0005_sensorinfo_delete_bodyinfo_delete_environmentinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
