# Generated by Django 4.1.7 on 2023-04-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycare_backend', '0006_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyStatusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_status', models.CharField(max_length=10)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HeartInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TempInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6)),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
